### PR TITLE
link to holding location and sort based on code

### LINKED ISSUE #41: Sort Holding Locations by holding code
Have the holding locations index view sort by holding location code rather than library code

### PR DESCRIPTION
**Pull request by tampakis**
Closes #41.

### CODE REVIEW

**Comment by jpstroop** [comment]
Why did the coverage drop so much?

**Comment by tampakis** [comment]
That's odd - it decided to include all of the engine-related files in the coverage this time. Can we configure coverage to ignore the files?
lib/locations/version.rb, lib/locations/engine.rb, lib/locations.rb, lib/generators/locations/install_generator.rb

The install_generator clearly works if the specs are able to run...

**Comment by escowles** [comment]
@tampakis: you can add filters to exclude stuff.  See https://github.com/pulibrary/plum/blob/master/spec/spec_helper.rb

**Comment by tampakis** [comment]
Thanks @escowles! Back to 100%

**Pull request merged**
